name: beacon
description: "A new Flutter project."
publish_to: 'none' # private package

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS style
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  nearby_connections: ^4.3.0
  permission_handler: ^12.0.1
  get: ^4.7.2
  flutter_map: ^8.2.1
  flutter_map_animations: ^0.9.0
  latlong2: ^0.9.1
  http: ^1.5.0
  geolocator: ^14.0.2
  sizer: ^3.1.3
  url_launcher: ^6.3.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_database: ^12.0.0
  flutter_animate: ^4.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# Launcher icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
