// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Li9djOh9xfyFlcKfIjGxFU06tHQLyyk',
    appId: '1:46627418820:web:1f0e0132abc9203e21cf91',
    messagingSenderId: '46627418820',
    projectId: 'laboffire',
    authDomain: 'laboffire.firebaseapp.com',
    databaseURL: 'https://laboffire-default-rtdb.firebaseio.com',
    storageBucket: 'laboffire.firebasestorage.app',
    measurementId: 'G-TT5FGEGNQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd3l8pVx_679WoJ8Fpgx9PRjiobDl_P_8',
    appId: '1:46627418820:android:c091bfd3879e681421cf91',
    messagingSenderId: '46627418820',
    projectId: 'laboffire',
    databaseURL: 'https://laboffire-default-rtdb.firebaseio.com',
    storageBucket: 'laboffire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSTvgy-yxBbFJBYoVqwOQH2Hmox6E4ux8',
    appId: '1:46627418820:ios:c10950b4c1df52bc21cf91',
    messagingSenderId: '46627418820',
    projectId: 'laboffire',
    databaseURL: 'https://laboffire-default-rtdb.firebaseio.com',
    storageBucket: 'laboffire.firebasestorage.app',
    iosBundleId: 'com.example.projectBeacon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSTvgy-yxBbFJBYoVqwOQH2Hmox6E4ux8',
    appId: '1:46627418820:ios:c10950b4c1df52bc21cf91',
    messagingSenderId: '46627418820',
    projectId: 'laboffire',
    databaseURL: 'https://laboffire-default-rtdb.firebaseio.com',
    storageBucket: 'laboffire.firebasestorage.app',
    iosBundleId: 'com.example.projectBeacon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5Li9djOh9xfyFlcKfIjGxFU06tHQLyyk',
    appId: '1:46627418820:web:97181260e4610d6021cf91',
    messagingSenderId: '46627418820',
    projectId: 'laboffire',
    authDomain: 'laboffire.firebaseapp.com',
    databaseURL: 'https://laboffire-default-rtdb.firebaseio.com',
    storageBucket: 'laboffire.firebasestorage.app',
    measurementId: 'G-WW8GMK6M1Q',
  );
}
